// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: arithmetic.proto
#ifndef GRPC_arithmetic_2eproto__INCLUDED
#define GRPC_arithmetic_2eproto__INCLUDED

#include "arithmetic.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace arithmetics {

class Arithmetics final {
 public:
  static constexpr char const* service_full_name() {
    return "arithmetics.Arithmetics";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Calculate(::grpc::ClientContext* context, const ::arithmetics::OperationRequest& request, ::arithmetics::OperationResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::arithmetics::OperationResponse>> AsyncCalculate(::grpc::ClientContext* context, const ::arithmetics::OperationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::arithmetics::OperationResponse>>(AsyncCalculateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::arithmetics::OperationResponse>> PrepareAsyncCalculate(::grpc::ClientContext* context, const ::arithmetics::OperationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::arithmetics::OperationResponse>>(PrepareAsyncCalculateRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Calculate(::grpc::ClientContext* context, const ::arithmetics::OperationRequest* request, ::arithmetics::OperationResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Calculate(::grpc::ClientContext* context, const ::arithmetics::OperationRequest* request, ::arithmetics::OperationResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::arithmetics::OperationResponse>* AsyncCalculateRaw(::grpc::ClientContext* context, const ::arithmetics::OperationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::arithmetics::OperationResponse>* PrepareAsyncCalculateRaw(::grpc::ClientContext* context, const ::arithmetics::OperationRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Calculate(::grpc::ClientContext* context, const ::arithmetics::OperationRequest& request, ::arithmetics::OperationResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::arithmetics::OperationResponse>> AsyncCalculate(::grpc::ClientContext* context, const ::arithmetics::OperationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::arithmetics::OperationResponse>>(AsyncCalculateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::arithmetics::OperationResponse>> PrepareAsyncCalculate(::grpc::ClientContext* context, const ::arithmetics::OperationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::arithmetics::OperationResponse>>(PrepareAsyncCalculateRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Calculate(::grpc::ClientContext* context, const ::arithmetics::OperationRequest* request, ::arithmetics::OperationResponse* response, std::function<void(::grpc::Status)>) override;
      void Calculate(::grpc::ClientContext* context, const ::arithmetics::OperationRequest* request, ::arithmetics::OperationResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::arithmetics::OperationResponse>* AsyncCalculateRaw(::grpc::ClientContext* context, const ::arithmetics::OperationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::arithmetics::OperationResponse>* PrepareAsyncCalculateRaw(::grpc::ClientContext* context, const ::arithmetics::OperationRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Calculate_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Calculate(::grpc::ServerContext* context, const ::arithmetics::OperationRequest* request, ::arithmetics::OperationResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Calculate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Calculate() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Calculate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Calculate(::grpc::ServerContext* /*context*/, const ::arithmetics::OperationRequest* /*request*/, ::arithmetics::OperationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCalculate(::grpc::ServerContext* context, ::arithmetics::OperationRequest* request, ::grpc::ServerAsyncResponseWriter< ::arithmetics::OperationResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Calculate<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Calculate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Calculate() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::arithmetics::OperationRequest, ::arithmetics::OperationResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::arithmetics::OperationRequest* request, ::arithmetics::OperationResponse* response) { return this->Calculate(context, request, response); }));}
    void SetMessageAllocatorFor_Calculate(
        ::grpc::MessageAllocator< ::arithmetics::OperationRequest, ::arithmetics::OperationResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::arithmetics::OperationRequest, ::arithmetics::OperationResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Calculate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Calculate(::grpc::ServerContext* /*context*/, const ::arithmetics::OperationRequest* /*request*/, ::arithmetics::OperationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Calculate(
      ::grpc::CallbackServerContext* /*context*/, const ::arithmetics::OperationRequest* /*request*/, ::arithmetics::OperationResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Calculate<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Calculate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Calculate() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Calculate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Calculate(::grpc::ServerContext* /*context*/, const ::arithmetics::OperationRequest* /*request*/, ::arithmetics::OperationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Calculate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Calculate() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Calculate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Calculate(::grpc::ServerContext* /*context*/, const ::arithmetics::OperationRequest* /*request*/, ::arithmetics::OperationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCalculate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Calculate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Calculate() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Calculate(context, request, response); }));
    }
    ~WithRawCallbackMethod_Calculate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Calculate(::grpc::ServerContext* /*context*/, const ::arithmetics::OperationRequest* /*request*/, ::arithmetics::OperationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Calculate(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Calculate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Calculate() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::arithmetics::OperationRequest, ::arithmetics::OperationResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::arithmetics::OperationRequest, ::arithmetics::OperationResponse>* streamer) {
                       return this->StreamedCalculate(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Calculate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Calculate(::grpc::ServerContext* /*context*/, const ::arithmetics::OperationRequest* /*request*/, ::arithmetics::OperationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCalculate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::arithmetics::OperationRequest,::arithmetics::OperationResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Calculate<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Calculate<Service > StreamedService;
};

}  // namespace arithmetics


#endif  // GRPC_arithmetic_2eproto__INCLUDED
