// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: arithmetic.proto

#include "arithmetic.pb.h"
#include "arithmetic.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace arithmetics {

static const char* Arithmetics_method_names[] = {
  "/arithmetics.Arithmetics/Calculate",
};

std::unique_ptr< Arithmetics::Stub> Arithmetics::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Arithmetics::Stub> stub(new Arithmetics::Stub(channel, options));
  return stub;
}

Arithmetics::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Calculate_(Arithmetics_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Arithmetics::Stub::Calculate(::grpc::ClientContext* context, const ::arithmetics::OperationRequest& request, ::arithmetics::OperationResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::arithmetics::OperationRequest, ::arithmetics::OperationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Calculate_, context, request, response);
}

void Arithmetics::Stub::async::Calculate(::grpc::ClientContext* context, const ::arithmetics::OperationRequest* request, ::arithmetics::OperationResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::arithmetics::OperationRequest, ::arithmetics::OperationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Calculate_, context, request, response, std::move(f));
}

void Arithmetics::Stub::async::Calculate(::grpc::ClientContext* context, const ::arithmetics::OperationRequest* request, ::arithmetics::OperationResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Calculate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::arithmetics::OperationResponse>* Arithmetics::Stub::PrepareAsyncCalculateRaw(::grpc::ClientContext* context, const ::arithmetics::OperationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::arithmetics::OperationResponse, ::arithmetics::OperationRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Calculate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::arithmetics::OperationResponse>* Arithmetics::Stub::AsyncCalculateRaw(::grpc::ClientContext* context, const ::arithmetics::OperationRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCalculateRaw(context, request, cq);
  result->StartCall();
  return result;
}

Arithmetics::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Arithmetics_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Arithmetics::Service, ::arithmetics::OperationRequest, ::arithmetics::OperationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Arithmetics::Service* service,
             ::grpc::ServerContext* ctx,
             const ::arithmetics::OperationRequest* req,
             ::arithmetics::OperationResponse* resp) {
               return service->Calculate(ctx, req, resp);
             }, this)));
}

Arithmetics::Service::~Service() {
}

::grpc::Status Arithmetics::Service::Calculate(::grpc::ServerContext* context, const ::arithmetics::OperationRequest* request, ::arithmetics::OperationResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace arithmetics

