// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: arithmetic.proto
// Protobuf C++ Version: 5.29.3

#include "arithmetic.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace arithmetics {

inline constexpr OperationResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : error_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        result_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR OperationResponse::OperationResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct OperationResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OperationResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OperationResponseDefaultTypeInternal() {}
  union {
    OperationResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OperationResponseDefaultTypeInternal _OperationResponse_default_instance_;

inline constexpr OperationRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : a_{0},
        b_{0},
        op_{static_cast< ::arithmetics::OperationRequest_Operation >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR OperationRequest::OperationRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct OperationRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OperationRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OperationRequestDefaultTypeInternal() {}
  union {
    OperationRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OperationRequestDefaultTypeInternal _OperationRequest_default_instance_;
}  // namespace arithmetics
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_arithmetic_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_arithmetic_2eproto = nullptr;
const ::uint32_t
    TableStruct_arithmetic_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::arithmetics::OperationRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::arithmetics::OperationRequest, _impl_.a_),
        PROTOBUF_FIELD_OFFSET(::arithmetics::OperationRequest, _impl_.b_),
        PROTOBUF_FIELD_OFFSET(::arithmetics::OperationRequest, _impl_.op_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::arithmetics::OperationResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::arithmetics::OperationResponse, _impl_.result_),
        PROTOBUF_FIELD_OFFSET(::arithmetics::OperationResponse, _impl_.error_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::arithmetics::OperationRequest)},
        {11, -1, -1, sizeof(::arithmetics::OperationResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::arithmetics::_OperationRequest_default_instance_._instance,
    &::arithmetics::_OperationResponse_default_instance_._instance,
};
const char descriptor_table_protodef_arithmetic_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020arithmetic.proto\022\013arithmetics\"\234\001\n\020Oper"
    "ationRequest\022\t\n\001a\030\001 \001(\001\022\t\n\001b\030\002 \001(\001\0223\n\002op"
    "\030\003 \001(\0162\'.arithmetics.OperationRequest.Op"
    "eration\"=\n\tOperation\022\007\n\003ADD\020\000\022\r\n\tSUBSTRA"
    "CT\020\001\022\014\n\010MULTIPLY\020\002\022\n\n\006DIVIDE\020\003\"2\n\021Operat"
    "ionResponse\022\016\n\006result\030\001 \001(\001\022\r\n\005error\030\002 \001"
    "(\t2[\n\013Arithmetics\022L\n\tCalculate\022\035.arithme"
    "tics.OperationRequest\032\036.arithmetics.Oper"
    "ationResponse\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_arithmetic_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_arithmetic_2eproto = {
    false,
    false,
    343,
    descriptor_table_protodef_arithmetic_2eproto,
    "arithmetic.proto",
    &descriptor_table_arithmetic_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_arithmetic_2eproto::offsets,
    file_level_enum_descriptors_arithmetic_2eproto,
    file_level_service_descriptors_arithmetic_2eproto,
};
namespace arithmetics {
const ::google::protobuf::EnumDescriptor* OperationRequest_Operation_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_arithmetic_2eproto);
  return file_level_enum_descriptors_arithmetic_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t OperationRequest_Operation_internal_data_[] = {
    262144u, 0u, };
bool OperationRequest_Operation_IsValid(int value) {
  return 0 <= value && value <= 3;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr OperationRequest_Operation OperationRequest::ADD;
constexpr OperationRequest_Operation OperationRequest::SUBSTRACT;
constexpr OperationRequest_Operation OperationRequest::MULTIPLY;
constexpr OperationRequest_Operation OperationRequest::DIVIDE;
constexpr OperationRequest_Operation OperationRequest::Operation_MIN;
constexpr OperationRequest_Operation OperationRequest::Operation_MAX;
constexpr int OperationRequest::Operation_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class OperationRequest::_Internal {
 public:
};

OperationRequest::OperationRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:arithmetics.OperationRequest)
}
OperationRequest::OperationRequest(
    ::google::protobuf::Arena* arena, const OperationRequest& from)
    : OperationRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE OperationRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void OperationRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, a_),
           0,
           offsetof(Impl_, op_) -
               offsetof(Impl_, a_) +
               sizeof(Impl_::op_));
}
OperationRequest::~OperationRequest() {
  // @@protoc_insertion_point(destructor:arithmetics.OperationRequest)
  SharedDtor(*this);
}
inline void OperationRequest::SharedDtor(MessageLite& self) {
  OperationRequest& this_ = static_cast<OperationRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* OperationRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) OperationRequest(arena);
}
constexpr auto OperationRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(OperationRequest),
                                            alignof(OperationRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull OperationRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_OperationRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &OperationRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<OperationRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &OperationRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<OperationRequest>(), &OperationRequest::ByteSizeLong,
            &OperationRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(OperationRequest, _impl_._cached_size_),
        false,
    },
    &OperationRequest::kDescriptorMethods,
    &descriptor_table_arithmetic_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* OperationRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> OperationRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::arithmetics::OperationRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // double a = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(OperationRequest, _impl_.a_)}},
    // double b = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(OperationRequest, _impl_.b_)}},
    // .arithmetics.OperationRequest.Operation op = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(OperationRequest, _impl_.op_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(OperationRequest, _impl_.op_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double a = 1;
    {PROTOBUF_FIELD_OFFSET(OperationRequest, _impl_.a_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double b = 2;
    {PROTOBUF_FIELD_OFFSET(OperationRequest, _impl_.b_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // .arithmetics.OperationRequest.Operation op = 3;
    {PROTOBUF_FIELD_OFFSET(OperationRequest, _impl_.op_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void OperationRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:arithmetics.OperationRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.a_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.op_) -
      reinterpret_cast<char*>(&_impl_.a_)) + sizeof(_impl_.op_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* OperationRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const OperationRequest& this_ = static_cast<const OperationRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* OperationRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const OperationRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:arithmetics.OperationRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // double a = 1;
          if (::absl::bit_cast<::uint64_t>(this_._internal_a()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                1, this_._internal_a(), target);
          }

          // double b = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_b()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_b(), target);
          }

          // .arithmetics.OperationRequest.Operation op = 3;
          if (this_._internal_op() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                3, this_._internal_op(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:arithmetics.OperationRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t OperationRequest::ByteSizeLong(const MessageLite& base) {
          const OperationRequest& this_ = static_cast<const OperationRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t OperationRequest::ByteSizeLong() const {
          const OperationRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:arithmetics.OperationRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // double a = 1;
            if (::absl::bit_cast<::uint64_t>(this_._internal_a()) != 0) {
              total_size += 9;
            }
            // double b = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_b()) != 0) {
              total_size += 9;
            }
            // .arithmetics.OperationRequest.Operation op = 3;
            if (this_._internal_op() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_op());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void OperationRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<OperationRequest*>(&to_msg);
  auto& from = static_cast<const OperationRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:arithmetics.OperationRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint64_t>(from._internal_a()) != 0) {
    _this->_impl_.a_ = from._impl_.a_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_b()) != 0) {
    _this->_impl_.b_ = from._impl_.b_;
  }
  if (from._internal_op() != 0) {
    _this->_impl_.op_ = from._impl_.op_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void OperationRequest::CopyFrom(const OperationRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:arithmetics.OperationRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void OperationRequest::InternalSwap(OperationRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(OperationRequest, _impl_.op_)
      + sizeof(OperationRequest::_impl_.op_)
      - PROTOBUF_FIELD_OFFSET(OperationRequest, _impl_.a_)>(
          reinterpret_cast<char*>(&_impl_.a_),
          reinterpret_cast<char*>(&other->_impl_.a_));
}

::google::protobuf::Metadata OperationRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class OperationResponse::_Internal {
 public:
};

OperationResponse::OperationResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:arithmetics.OperationResponse)
}
inline PROTOBUF_NDEBUG_INLINE OperationResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::arithmetics::OperationResponse& from_msg)
      : error_(arena, from.error_),
        _cached_size_{0} {}

OperationResponse::OperationResponse(
    ::google::protobuf::Arena* arena,
    const OperationResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  OperationResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.result_ = from._impl_.result_;

  // @@protoc_insertion_point(copy_constructor:arithmetics.OperationResponse)
}
inline PROTOBUF_NDEBUG_INLINE OperationResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : error_(arena),
        _cached_size_{0} {}

inline void OperationResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.result_ = {};
}
OperationResponse::~OperationResponse() {
  // @@protoc_insertion_point(destructor:arithmetics.OperationResponse)
  SharedDtor(*this);
}
inline void OperationResponse::SharedDtor(MessageLite& self) {
  OperationResponse& this_ = static_cast<OperationResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.error_.Destroy();
  this_._impl_.~Impl_();
}

inline void* OperationResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) OperationResponse(arena);
}
constexpr auto OperationResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(OperationResponse),
                                            alignof(OperationResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull OperationResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_OperationResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &OperationResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<OperationResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &OperationResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<OperationResponse>(), &OperationResponse::ByteSizeLong,
            &OperationResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(OperationResponse, _impl_._cached_size_),
        false,
    },
    &OperationResponse::kDescriptorMethods,
    &descriptor_table_arithmetic_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* OperationResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 43, 2> OperationResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::arithmetics::OperationResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string error = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(OperationResponse, _impl_.error_)}},
    // double result = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(OperationResponse, _impl_.result_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double result = 1;
    {PROTOBUF_FIELD_OFFSET(OperationResponse, _impl_.result_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // string error = 2;
    {PROTOBUF_FIELD_OFFSET(OperationResponse, _impl_.error_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\35\0\5\0\0\0\0\0"
    "arithmetics.OperationResponse"
    "error"
  }},
};

PROTOBUF_NOINLINE void OperationResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:arithmetics.OperationResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_.ClearToEmpty();
  _impl_.result_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* OperationResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const OperationResponse& this_ = static_cast<const OperationResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* OperationResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const OperationResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:arithmetics.OperationResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // double result = 1;
          if (::absl::bit_cast<::uint64_t>(this_._internal_result()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                1, this_._internal_result(), target);
          }

          // string error = 2;
          if (!this_._internal_error().empty()) {
            const std::string& _s = this_._internal_error();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "arithmetics.OperationResponse.error");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:arithmetics.OperationResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t OperationResponse::ByteSizeLong(const MessageLite& base) {
          const OperationResponse& this_ = static_cast<const OperationResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t OperationResponse::ByteSizeLong() const {
          const OperationResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:arithmetics.OperationResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string error = 2;
            if (!this_._internal_error().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_error());
            }
            // double result = 1;
            if (::absl::bit_cast<::uint64_t>(this_._internal_result()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void OperationResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<OperationResponse*>(&to_msg);
  auto& from = static_cast<const OperationResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:arithmetics.OperationResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_error().empty()) {
    _this->_internal_set_error(from._internal_error());
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_result()) != 0) {
    _this->_impl_.result_ = from._impl_.result_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void OperationResponse::CopyFrom(const OperationResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:arithmetics.OperationResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void OperationResponse::InternalSwap(OperationResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.error_, &other->_impl_.error_, arena);
        swap(_impl_.result_, other->_impl_.result_);
}

::google::protobuf::Metadata OperationResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace arithmetics
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_arithmetic_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
